# docker-compose.yml
version: '3.5'
services:
  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://user:pass@postgres:5432/db
      NODE_ENV: development
      PORT: 3000
    ports:
      - "3000:3000"
    command: npm run dev
    volumes:
      - .:/app/
      - /app/node_modules

  db:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_DB: open-data-paris
      POSTGRES_USER: postgres
    ports:
      - "7200:5432"
    volumes:
      - ./sql_import:/app/
